[application]
	host = "0.0.0.0"
	port = 8000
[database]
	host = "127.0.0.1"
	port = 5432
	username = "jamie"
	password = "jamie"
	database_name = "newsletter"
	require_ssl = false
[email_client]
	base_url = "localhost"
	sender_email = "hello@madebyjamie.com"
	authorization_token = "my-secret-token"
	timeout_milliseconds = 10000