application_port = 8000
[database]
	host = "127.0.0.1"
	port = 5432
	username = "jamie"
	password = "jamie"
	database_name = "newsletter"
[email_client]
	base_url = "https://api.postmarkapp.com"
	sender_email = "hello@madebyjamie.com"